// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 17.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Intent.Modules.Angular.Templates.Module.AngularRoutingModule
{
    using System.Collections.Generic;
    using System.Linq;
    using Intent.Modules.Common;
    using Intent.Modules.Common.TypeScript.Templates;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\Dev\Intent.Modules.Web\Modules\Intent.Modules.Angular\Templates\Module\AngularRoutingModule\AngularRoutingModuleTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "17.0.0.0")]
    public partial class AngularRoutingModuleTemplate : TypeScriptTemplateBase<Intent.Modelers.WebClient.Angular.Api.RoutingModel>
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            this.Write("import { NgModule } from \'@angular/core\';\r\nimport { RouterModule, Routes } from \'" +
                    "@angular/router\';\r\n\r\nconst routes: Routes = [\r\n");
            
            #line 11 "C:\Dev\Intent.Modules.Web\Modules\Intent.Modules.Angular\Templates\Module\AngularRoutingModule\AngularRoutingModuleTemplate.tt"
  foreach(var redirect in Model.Redirects) { 
            
            #line default
            #line hidden
            this.Write("  {\r\n    path: \'");
            
            #line 13 "C:\Dev\Intent.Modules.Web\Modules\Intent.Modules.Angular\Templates\Module\AngularRoutingModule\AngularRoutingModuleTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(redirect.Name));
            
            #line default
            #line hidden
            this.Write("\',\r\n    redirectTo: \'");
            
            #line 14 "C:\Dev\Intent.Modules.Web\Modules\Intent.Modules.Angular\Templates\Module\AngularRoutingModule\AngularRoutingModuleTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(redirect.RedirectTo));
            
            #line default
            #line hidden
            this.Write("\'");
            
            #line 14 "C:\Dev\Intent.Modules.Web\Modules\Intent.Modules.Angular\Templates\Module\AngularRoutingModule\AngularRoutingModuleTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(string.IsNullOrEmpty(redirect.Name) && Model.Module.IsRootModule() ? @",
    pathMatch: 'full'" : ""));
            
            #line default
            #line hidden
            this.Write("\r\n  },\r\n");
            
            #line 17 "C:\Dev\Intent.Modules.Web\Modules\Intent.Modules.Angular\Templates\Module\AngularRoutingModule\AngularRoutingModuleTemplate.tt"
  } 
            
            #line default
            #line hidden
            
            #line 18 "C:\Dev\Intent.Modules.Web\Modules\Intent.Modules.Angular\Templates\Module\AngularRoutingModule\AngularRoutingModuleTemplate.tt"
 foreach(var route in Model.Routes.Where(x => x.RoutesToComponent)) {
            
            #line default
            #line hidden
            this.Write("  {\r\n    path: \'");
            
            #line 20 "C:\Dev\Intent.Modules.Web\Modules\Intent.Modules.Angular\Templates\Module\AngularRoutingModule\AngularRoutingModuleTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetRoute(route)));
            
            #line default
            #line hidden
            this.Write("\',\r\n    component: ");
            
            #line 21 "C:\Dev\Intent.Modules.Web\Modules\Intent.Modules.Angular\Templates\Module\AngularRoutingModule\AngularRoutingModuleTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetTypeName(route)));
            
            #line default
            #line hidden
            this.Write("\r\n  },\r\n");
            
            #line 23 "C:\Dev\Intent.Modules.Web\Modules\Intent.Modules.Angular\Templates\Module\AngularRoutingModule\AngularRoutingModuleTemplate.tt"
 } 
            
            #line default
            #line hidden
            
            #line 24 "C:\Dev\Intent.Modules.Web\Modules\Intent.Modules.Angular\Templates\Module\AngularRoutingModule\AngularRoutingModuleTemplate.tt"
 foreach(var route in Model.Routes.Where(x => x.RoutesToModule)) {
            
            #line default
            #line hidden
            this.Write("  {\r\n    path: \'");
            
            #line 26 "C:\Dev\Intent.Modules.Web\Modules\Intent.Modules.Angular\Templates\Module\AngularRoutingModule\AngularRoutingModuleTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetRoute(route)));
            
            #line default
            #line hidden
            this.Write("\',\r\n    loadChildren: () => import(\'./");
            
            #line 27 "C:\Dev\Intent.Modules.Web\Modules\Intent.Modules.Angular\Templates\Module\AngularRoutingModule\AngularRoutingModuleTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetModulePath(route)));
            
            #line default
            #line hidden
            this.Write("\').then(x => x.");
            
            #line 27 "C:\Dev\Intent.Modules.Web\Modules\Intent.Modules.Angular\Templates\Module\AngularRoutingModule\AngularRoutingModuleTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetModuleClassName(route)));
            
            #line default
            #line hidden
            this.Write(")\r\n  },\r\n");
            
            #line 29 "C:\Dev\Intent.Modules.Web\Modules\Intent.Modules.Angular\Templates\Module\AngularRoutingModule\AngularRoutingModuleTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("];\r\n\r\n@NgModule({\r\n  imports: [");
            
            #line 33 "C:\Dev\Intent.Modules.Web\Modules\Intent.Modules.Angular\Templates\Module\AngularRoutingModule\AngularRoutingModuleTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetNgModuleImports()));
            
            #line default
            #line hidden
            this.Write("],\r\n  exports: [RouterModule]\r\n})\r\nexport class ");
            
            #line 36 "C:\Dev\Intent.Modules.Web\Modules\Intent.Modules.Angular\Templates\Module\AngularRoutingModule\AngularRoutingModuleTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ClassName));
            
            #line default
            #line hidden
            this.Write(" { }\r\n");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
}
