//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Intent.Modules.Angular.Layout.modelers {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.14.0.0")]
    internal sealed partial class Angular_Layout_Extensions : global::System.Configuration.ApplicationSettingsBase {
        
        private static Angular_Layout_Extensions defaultInstance = ((Angular_Layout_Extensions)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Angular_Layout_Extensions())));
        
        public static Angular_Layout_Extensions Default {
            get {
                return defaultInstance;
            }
        }
    }
}
