// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 16.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Intent.Modules.Angular.Layout.Decorators.Controls.Navbar
{
    using System.Collections.Generic;
    using System.Linq;
    using Intent.Modules.Common;
    using Intent.Modules.Common.Templates;
    using Intent.Angular.Layout.Api;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\Dev\Intent.Modules.Web\Intent.Modules.Angular.Layout\Decorators\Controls\Navbar\NavbarTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "16.0.0.0")]
    public partial class NavbarTemplate : T4TemplateBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            this.Write("<nav class=\"navbar navbar-expand-lg navbar-light bg-light\" role=\"navigation\" inte" +
                    "nt-manage=\"\" intent-id=\"");
            
            #line 8 "C:\Dev\Intent.Modules.Web\Intent.Modules.Angular.Layout\Decorators\Controls\Navbar\NavbarTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.Id));
            
            #line default
            #line hidden
            this.Write("\">\r\n  <div class=\"navbar-header\">\r\n    <a class=\"navbar-brand\" href=\"#\"><span>");
            
            #line 10 "C:\Dev\Intent.Modules.Web\Intent.Modules.Angular.Layout\Decorators\Controls\Navbar\NavbarTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Application.Name));
            
            #line default
            #line hidden
            this.Write(@"</span></a>
  </div>
  <button class=""navbar-toggler"" type=""button"" (click)=""isCollapsed = !isCollapsed"" aria-controls=""navbarNav"" aria-expanded=""false"" aria-label=""Toggle navigation"">
    <span class=""navbar-toggler-icon""></span>
  </button>
  <div class=""collapse navbar-collapse"" [collapse]=""isCollapsed"">
    <ul class=""nav navbar-nav"" intent-manage="""" intent-id=""navbar-nav"">
");
            
            #line 17 "C:\Dev\Intent.Modules.Web\Intent.Modules.Angular.Layout\Decorators\Controls\Navbar\NavbarTemplate.tt"
  foreach(var navItem in Model.InternalElement.ChildElements.OrderBy(x => x.Order)) { 
            
            #line default
            #line hidden
            
            #line 18 "C:\Dev\Intent.Modules.Web\Intent.Modules.Angular.Layout\Decorators\Controls\Navbar\NavbarTemplate.tt"
      if (navItem.IsLink()) {
            var linkModel = navItem.AsLinkModel(); 
            
            #line default
            #line hidden
            this.Write("      <li class=\"nav-item\" intent-id=\"");
            
            #line 20 "C:\Dev\Intent.Modules.Web\Intent.Modules.Angular.Layout\Decorators\Controls\Navbar\NavbarTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(navItem.Id));
            
            #line default
            #line hidden
            this.Write("\">\r\n        <a class=\"nav-link\" routerLink=\"");
            
            #line 21 "C:\Dev\Intent.Modules.Web\Intent.Modules.Angular.Layout\Decorators\Controls\Navbar\NavbarTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(linkModel.GetLinkSettings().RouterLink()));
            
            #line default
            #line hidden
            this.Write("\" routerLinkActive=\"active\">\r\n          <span class=\"glyphicon glyphicon-th-list\"" +
                    " aria-hidden=\"true\"></span>\r\n          <span>");
            
            #line 23 "C:\Dev\Intent.Modules.Web\Intent.Modules.Angular.Layout\Decorators\Controls\Navbar\NavbarTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(linkModel.Name));
            
            #line default
            #line hidden
            this.Write("</span>\r\n        </a>\r\n      </li>\r\n");
            
            #line 26 "C:\Dev\Intent.Modules.Web\Intent.Modules.Angular.Layout\Decorators\Controls\Navbar\NavbarTemplate.tt"
      } 
            
            #line default
            #line hidden
            
            #line 27 "C:\Dev\Intent.Modules.Web\Intent.Modules.Angular.Layout\Decorators\Controls\Navbar\NavbarTemplate.tt"
      else if (navItem.IsDropdown()) {
            var dropdownModel = navItem.AsDropdownModel(); 
            
            #line default
            #line hidden
            this.Write("      <li class=\"dropdown nav-item\" dropdown intent-id=\"");
            
            #line 29 "C:\Dev\Intent.Modules.Web\Intent.Modules.Angular.Layout\Decorators\Controls\Navbar\NavbarTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(navItem.Id));
            
            #line default
            #line hidden
            this.Write("\">\r\n        <a class=\"nav-link dropdown-toggle\" data-toggle=\"dropdown\" role=\"butt" +
                    "on\" aria-haspopup=\"true\" aria-expanded=\"false\" dropdownToggle>");
            
            #line 30 "C:\Dev\Intent.Modules.Web\Intent.Modules.Angular.Layout\Decorators\Controls\Navbar\NavbarTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(dropdownModel.Name));
            
            #line default
            #line hidden
            this.Write("<span class=\"caret\"></span>\r\n        </a>\r\n        <div class=\"dropdown-menu\" *dr" +
                    "opdownMenu>\r\n");
            
            #line 33 "C:\Dev\Intent.Modules.Web\Intent.Modules.Angular.Layout\Decorators\Controls\Navbar\NavbarTemplate.tt"
        foreach(var linkModel in dropdownModel.Links) { 
            
            #line default
            #line hidden
            this.Write("          <a class=\"dropdown-item\" routerLink=\"");
            
            #line 34 "C:\Dev\Intent.Modules.Web\Intent.Modules.Angular.Layout\Decorators\Controls\Navbar\NavbarTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(linkModel.GetLinkSettings().RouterLink()));
            
            #line default
            #line hidden
            this.Write("\"><span class=\"glyphicon glyphicon-search\" aria-hidden=\"true\"></span><span> ");
            
            #line 34 "C:\Dev\Intent.Modules.Web\Intent.Modules.Angular.Layout\Decorators\Controls\Navbar\NavbarTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(linkModel.Name));
            
            #line default
            #line hidden
            this.Write("</span></a>\r\n");
            
            #line 35 "C:\Dev\Intent.Modules.Web\Intent.Modules.Angular.Layout\Decorators\Controls\Navbar\NavbarTemplate.tt"
        } 
            
            #line default
            #line hidden
            this.Write("        </div>\r\n      </li>\r\n");
            
            #line 38 "C:\Dev\Intent.Modules.Web\Intent.Modules.Angular.Layout\Decorators\Controls\Navbar\NavbarTemplate.tt"
      } 
            
            #line default
            #line hidden
            
            #line 39 "C:\Dev\Intent.Modules.Web\Intent.Modules.Angular.Layout\Decorators\Controls\Navbar\NavbarTemplate.tt"
      else { 
            
            #line default
            #line hidden
            this.Write("      <li class=\"nav-item\" intent-id=\"");
            
            #line 40 "C:\Dev\Intent.Modules.Web\Intent.Modules.Angular.Layout\Decorators\Controls\Navbar\NavbarTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(navItem.Id));
            
            #line default
            #line hidden
            this.Write("\">\r\n");
            
            #line 41 "C:\Dev\Intent.Modules.Web\Intent.Modules.Angular.Layout\Decorators\Controls\Navbar\NavbarTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ControlWriter.WriteControl(navItem, "        ")));
            
            #line default
            #line hidden
            this.Write("\r\n      </li>\r\n");
            
            #line 43 "C:\Dev\Intent.Modules.Web\Intent.Modules.Angular.Layout\Decorators\Controls\Navbar\NavbarTemplate.tt"
      } 
            
            #line default
            #line hidden
            
            #line 44 "C:\Dev\Intent.Modules.Web\Intent.Modules.Angular.Layout\Decorators\Controls\Navbar\NavbarTemplate.tt"
  } 
            
            #line default
            #line hidden
            this.Write("    </ul>\r\n  </div>\r\n</nav>");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
}
