// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 18.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Intent.Modules.Angular.Templates.Component.LayoutCompeonentHtml
{
    using System.Collections.Generic;
    using System.Linq;
    using Intent.Modules.Common;
    using Intent.Modules.Common.Templates;
    using Intent.Modules.Common.Html.Templates;
    using Intent.Templates;
    using Intent.Metadata.Models;
    using Intent.Modelers.UI.Api;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "D:\Dev\Intent.Modules.Web\Modules\Intent.Modules.Angular\Templates\Component\LayoutCompeonentHtml\LayoutCompeonentHtmlTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "18.0.0.0")]
    public partial class LayoutCompeonentHtmlTemplate : HtmlTemplateBase<Intent.Modelers.UI.Api.LayoutModel>
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            this.Write("\r\n<\r\n<body>\r\n    <div class=\"sidebar\">\r\n        <h2>Menu</h2>\r\n        <nav>\r\n");
            
            #line 17 "D:\Dev\Intent.Modules.Web\Modules\Intent.Modules.Angular\Templates\Component\LayoutCompeonentHtml\LayoutCompeonentHtmlTemplate.tt"

    foreach (var item in Model.Sider.InternalElement.ChildElements)
    {

            
            #line default
            #line hidden
            this.Write("            <a href=\"");
            
            #line 21 "D:\Dev\Intent.Modules.Web\Modules\Intent.Modules.Angular\Templates\Component\LayoutCompeonentHtml\LayoutCompeonentHtmlTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write("\">");
            
            #line 21 "D:\Dev\Intent.Modules.Web\Modules\Intent.Modules.Angular\Templates\Component\LayoutCompeonentHtml\LayoutCompeonentHtmlTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write("</a>\r\n");
            
            #line 22 "D:\Dev\Intent.Modules.Web\Modules\Intent.Modules.Angular\Templates\Component\LayoutCompeonentHtml\LayoutCompeonentHtmlTemplate.tt"

    }

            
            #line default
            #line hidden
            this.Write("        </nav>\r\n    </div>\r\n</body>\r\n");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
}
