// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 16.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Intent.Modules.Angular.Templates.Module.AngularResolver
{
    using System.Collections.Generic;
    using System.Linq;
    using Intent.Modules.Common;
    using Intent.Modules.Common.Templates;
    using Intent.Modules.Common.TypeScript.Templates;
    using Intent.Templates;
    using Intent.Metadata.Models;
    using Intent.Modelers.WebClient.Angular.Api;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\Dev\Intent.Modules.Web\Intent.Modules.Angular\Templates\Module\AngularResolver\AngularResolverTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "16.0.0.0")]
    public partial class AngularResolverTemplate : TypeScriptTemplateBase<Intent.Modelers.WebClient.Angular.Api.ResolverModel>
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            this.Write("import {ActivatedRouteSnapshot, Resolve, RouterStateSnapshot} from \'@angular/rout" +
                    "er\';\r\nimport {Observable} from \'rxjs\';\r\nimport {Injectable} from \'@angular/core\'" +
                    ";\r\n\r\n@Injectable()\r\nexport class ");
            
            #line 16 "C:\Dev\Intent.Modules.Web\Intent.Modules.Angular\Templates\Module\AngularResolver\AngularResolverTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ClassName));
            
            #line default
            #line hidden
            this.Write(" implements Resolve<");
            
            #line 16 "C:\Dev\Intent.Modules.Web\Intent.Modules.Angular\Templates\Module\AngularResolver\AngularResolverTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetTypeName(Model.TypeReference)));
            
            #line default
            #line hidden
            this.Write("> {\r\n\r\n  // @IntentCanAdd()\r\n  constructor() { }\r\n\r\n  ");
            
            #line 21 "C:\Dev\Intent.Modules.Web\Intent.Modules.Angular\Templates\Module\AngularResolver\AngularResolverTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.IntentIgnoreBodyDecorator()));
            
            #line default
            #line hidden
            this.Write("\r\n  resolve(route: ActivatedRouteSnapshot, state: RouterStateSnapshot): Observabl" +
                    "e<");
            
            #line 22 "C:\Dev\Intent.Modules.Web\Intent.Modules.Angular\Templates\Module\AngularResolver\AngularResolverTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetTypeName(Model.TypeReference)));
            
            #line default
            #line hidden
            this.Write("> | Promise<");
            
            #line 22 "C:\Dev\Intent.Modules.Web\Intent.Modules.Angular\Templates\Module\AngularResolver\AngularResolverTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetTypeName(Model.TypeReference)));
            
            #line default
            #line hidden
            this.Write("> | ");
            
            #line 22 "C:\Dev\Intent.Modules.Web\Intent.Modules.Angular\Templates\Module\AngularResolver\AngularResolverTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetTypeName(Model.TypeReference)));
            
            #line default
            #line hidden
            this.Write(" {\r\n  \r\n  }\r\n}\r\n");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
}
