<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Intent.Modules.Common" Version="3.11.7" />
    <PackageReference Include="Intent.Modules.Common.TypeScript" Version="4.1.6" />
    <PackageReference Include="Intent.Modules.Metadata.WebApi" Version="4.7.21" />
    <PackageReference Include="Intent.Modules.Modelers.Services" Version="4.0.16" />
    <PackageReference Include="Intent.Modules.Modelers.Types.ServiceProxies" Version="5.5.6" />
    <PackageReference Include="Intent.Modules.Modelers.UI" Version="1.1.5" />
    <PackageReference Include="Intent.Packager" Version="3.6.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Intent.RoslynWeaver.Attributes" Version="3.0.0" />
    <PackageReference Include="Intent.SoftwareFactory.SDK" Version="3.14.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Intent.Modules.AngularConstants\Intent.Modules.AngularConstants.csproj" />
  </ItemGroup>

</Project>