// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 16.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Intent.Modules.TypeScript.Proxies.Contracts.Templates.DTO
{
    using System.Collections.Generic;
    using System.Linq;
    using Intent.Modules.Common;
    using Intent.Modules.Common.Templates;
    using Intent.Modules.Common.TypeScript.Templates;
    using Intent.Templates;
    using Intent.Metadata.Models;
    using Intent.Modelers.Types.ServiceProxies.Api;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\Dev\Intent.Modules.Web\Intent.Modules.TypeScript.Proxies.Contracts\Templates\DTO\DTOTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "16.0.0.0")]
    public partial class DTOTemplate : TypeScriptTemplateBase<ServiceProxyDTOModel>
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            this.Write("\r\nexport interface ");
            
            #line 12 "C:\Dev\Intent.Modules.Web\Intent.Modules.TypeScript.Proxies.Contracts\Templates\DTO\DTOTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ClassName));
            
            #line default
            #line hidden
            
            #line 12 "C:\Dev\Intent.Modules.Web\Intent.Modules.TypeScript.Proxies.Contracts\Templates\DTO\DTOTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GenericTypes));
            
            #line default
            #line hidden
            this.Write(" {\r\n");
            
            #line 13 "C:\Dev\Intent.Modules.Web\Intent.Modules.TypeScript.Proxies.Contracts\Templates\DTO\DTOTemplate.tt"
  foreach (var field in Model.Fields) { 
            
            #line default
            #line hidden
            this.Write("    ");
            
            #line 14 "C:\Dev\Intent.Modules.Web\Intent.Modules.TypeScript.Proxies.Contracts\Templates\DTO\DTOTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(field.Name.ToCamelCase()));
            
            #line default
            #line hidden
            
            #line 14 "C:\Dev\Intent.Modules.Web\Intent.Modules.TypeScript.Proxies.Contracts\Templates\DTO\DTOTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(field.TypeReference.IsNullable ? "?" : ""));
            
            #line default
            #line hidden
            this.Write(": ");
            
            #line 14 "C:\Dev\Intent.Modules.Web\Intent.Modules.TypeScript.Proxies.Contracts\Templates\DTO\DTOTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.GetTypeName(field)));
            
            #line default
            #line hidden
            this.Write(";\r\n");
            
            #line 15 "C:\Dev\Intent.Modules.Web\Intent.Modules.TypeScript.Proxies.Contracts\Templates\DTO\DTOTemplate.tt"
  } 
            
            #line default
            #line hidden
            this.Write("}\r\n");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
}
